apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/backend-config: '{"ports": {"60000":"pdm-backendconfig"}}'
  name: dspdmservice
spec:
  type: NodePort
  selector:
    app: dspdmservice
    role: backend
    env: production
  ports:
  - protocol: TCP
    port: 60000
    targetPort: 8080
    nodePort: 32703
