= Data Classification

In the oil & gas industry, data is a big term. It encompasses many
aspects of E&P activities - exploration, appraisal, drilling,
development, and production. There are many ways that we can classify
the data, such as by data type (document, time series, logs, 3D
geological model), By its structure ( structure data, semi-structured
data, unstructured data), and more.

In PDM365, we classify the data into the following category: Master
Data,Operational Data and Real-time Data We also plan to store Models.

== Master Data

Master data includes entities that are either static and/or rarely
change over the life or the field. It includes:

* Area
* Field
* Pool/Reservoir
* Formation
* Zone
* Platform
* Well, Wellbore, and Well Completion
* Well Tubular
* Network
* Pipeline
* Facilities
* Equipment, including well equipment (tubular, pumps)
* Business Associate +

While well and completions may change after workover, pumps may be
switched, and network may be expanded, the frequency of the changes are
nowhere near daily or monthly. The latter is categorized into
operational data.

Master data hierarchy and data model in PDM365 can be seen in _Master
Data_(_Web view_)


== Operational Data

Operational data includes data that regularly and frequently change such
as:

* Production and injection volumes – daily and monthly
* Well Test Data
* Well Production Aggregate
* Well Activities – workover, recompletion, re-entry, etc.
* Well History-Well status history and production method history

== Reference Data

Reference data are data that define the set of permissible values to be
used by other data fields. Reference data gain in value when they are
widely reused and widely referenced. Typically, they do not change
overly much in terms of definition, apart from occasional.


== Real-time Data

​Real-time data consists of information delivered immediately after
collection with little to no delay. +
​It can be primary data such as pressure and temperature, or calculated
data such as flow rate.

== Models

​ Models are the representation of a physical object, such as reservoir
or rock/fluid properties (PVT).

​ In PDM365, we plan to store Nexus network model, Nexus reservoir model
and PVT model, indexed by scenario.
