= Data Model - Overview

*What this documentation is for*

This documentation captures the data model that is implemented in the
DecisionSpace 365 Production Data Management. This documentation is live
- we are actively adding and extending the data model, and the additions
will be documented here.

*How we design PDM365 data model*

We prioritize *performance* and *extensibility* when designing the data
model.

*Performance* means being fast. The data model should _not_ be too
excessive and complicated to the point that it slows down processes and
queries, but still structured enough for fast indexing.

*Extensibility* means that the PDM365 data model provides a core
definition that can be extended in a maintainable and sustainable way,
over the life of the field. We are aware that trying to define _all_
possible entities and attributes throughout many kinds of assets and
operations is a never-ending quest. With the PDM365 data model and
application, new entities and attributes can be added and maintained
out-of-the-box.

The standards that we consider and examine when defining the data model
structure are:

* Project data management system - Openworks
* Landmark Common Model - LCM
* PPDM
* OSDU (Open Subsurface Data Universe)
* PE Data Model (from DS Prod Engineer)
* PPDM-modified (from DS Prod Allocation)
+
For entity definition, table names, and attribute definitions and
constraints, we adhere to PPDM definition with minor modifications. The
modifications are noted in this data model documentation.
+
For example, we follow PPDM definition to use ``Pool'' and its
definition__(POOL: Represents a reservoir or a group of small tracts of
land brought together for the granting of a well permit under applicable
spacing rules__)_._ However, we also modify it into ``Pool/Reservoir''
because the”Pool” terminology is not widely used outside North America.
+
*PPDM and OSDU standards – how they relate to PDM365 data model*
+
https://ppdm.org/ppdm/PPDM/IPDS/PPDM_Data_Model/PPDM/PPDM_3.9_Data_Model.aspx?hkey=c8aed1ca-aa85-409e-8d89-74b42a6d2a18[PPDM]
has developed the industry standard and an extensive guideline on
petroleum data model definition since 1988.
https://www.opengroup.org/osdu/forum-homepage[OSDU] is the new industry
initiative led by supermajors (BP, Chevron, Total, among others) to
develop a standard data platform for the oil and gas industry, which
will reduce silos and put data at the center of the subsurface
community. One of the scope is to define a common data model and schema,
which is still under iteration until today.

When developing our core data model, we examine PPDM 3.9 standard
closely. We adhere to their entity definitions, table names, attribute
definitions, and attribute constraints. However, we rethink the approach
of the highly normalized table structure that comes with the standard,
to ensure performance and extensibility taking priority over
completeness/complexity. We seek to simplify the data structure and
tables, reduce data redundancy and ensure consistency.

The
https://ppdm.org/ppdm/PPDM/IPDS/PPDM_Data_Model/PPDM/PPDM_3.9_Data_Model.aspx?hkey=c8aed1ca-aa85-409e-8d89-74b42a6d2a18[PPDM3.9]
is on PPDM website (membership required). The PDF version is available
for v3.8.

We also pick and choose most commonly used entities, tables, and
attributes to be included in our PDM365 core production data model. At
the same time, we leave plenty of room for customer-specific extensions
and customizations, acknowledging that producing assets are inherently
unique.

On OSDU, we are closely monitoring the progress of the data modeling.
It’s important to note that OSDU data definition is still under
iteration. There is no final or approved standard yet. Also, as per
January 2020, they have been iterating up until well, tubular comma and
completions. We are planning to volunteer when they start working on
production data.
