= Index All for Specific Business Object

You can index all data for specific business object into `bo_search` table by sending the following request with Post method.

* If any data for the specific Business Object in `bo_search` table, then firstly clear all those data in `bo_search` table, and then insert records of the except metadata and `bo_search` into it.
* If NO data for the Business Object in `bo_search` table, then insert records of that table except metadata and `bo_search` into it directly.

== 1. Request URL

/{PDM Server domain}/search/indexAll/{boName}

*Method：* Post

== 2. Request headers

[cols=",",options="header",]
|===
|Name |Value
|Content-Type |application/json
|===

== 3. Request body

Below request will clear all index and re-index for Business Object `AREA`.

++++
<details>
<summary><font style="color: blue; cursor: pointer; text-decoration:underline; background-color: 	#F0F8FF">Try it my self </font>
</summary>
<iframe src="./_attachments/search-index-specific-business-object/search-index-specific-business-object.html" width="600px" height="620px"> </iframe>
</details>
++++

== 4. Responses

.Response
[example]
====
[source,json]
----
{
    "status": {
        "statusCode": 1,
        "statusLabel": "Success"
    },
        "messages": [
        {
            "message": "999 record(s) deleted from BO SEARCH successfully for business object 'AREA'.",
            "status": {
                "statusCode": 1,
                "statusLabel": "Success"
            }
        }
    ],
    "messages": [
        {
            "message": "10000 record(s) inserted in BO SEARCH successfully for business object 'AREA'.",
            "status": {
                "statusCode": 1,
                "statusLabel": "Success"
            }
        }
    ],
    "exception": {},
    "data": {},
    "version": "0.0.0.0A",
    "threadName": "**system_32486",
    "requestTime": "2021-05-19 10:47:40.865 +08:00",
    "responseTime": "2021-05-19 10:48:58.854 +08:00"
}
----
====
== 4. Responses

Please see xref:responses.adoc[Responses]
