= Use the Search API to Search Data

API provides search features, include search with exact match and search with like match.

In this document, let’s see, how to use the search API to search Data.

=== New Entity in PDM (BO_SEARCH)

A new entity is introduced in PDM named as BO_SEARCH. This is the metadata table and business_object_attr contains information of this table. Columns details are below.

*BO_SEARCH_ID*: Primary key for this table. It is an auto increment key. Postgres will handle that itself.

*BO_NAME*: Business object name. For example if you are inserting WELL then this BO_NAME should have WELL inside it.

*PK_BO_ATTR_NAMES*: Primary key column names for particular business object. For example, in case of WELL, WELL_ID is its primary key column name. So this should have WELL_ID inside it.

*PK_BO_ATTR_VALUES*: Primary key column value for particular business object. For example, in case of WELL. WELL_ID is the primary key and the value could be any integer let’s say 100. So this should have 100 inside it.

*SEARCH_JSONB*: The actual well data without keys. This should have Json array which contains well entries. (This is for searching the particular data for given business object).

*OBJECT_JSONB*: The actual well data with keys. This column is mainly used for ordering the search results based on the column selected in the request.

*ROW_CHANGED_BY*: Username of system user.

*ROW_CHANGED_DATE:* Timestamp of changed event.

=== Integration with PDM services

BO_SEARCH is the metadata table so it is not allowed to access externally for creation/update/deletion. So only PDM services can insert into this table. So it is integrated with PDM save or delete services.

=== How to search results using PDM search service?

BO_SEARCH contains the business object data with keys and without keys. So you can search with your required keywords against the business object name like `WELL'.

There are two ways implemented for search.

* Exact search

For this search, need to use JSONB_FIND_EXACT operator.

* Like search

For this search, need to use JSONB_FIND_LIKE operator.

So in order to search results for particular business object you can use this api.
