= What's new

== What’s new in Joint MVP3.0 - November 2020

* Integrate with DSIS unit conversion service and support unit conversion.
* PDM data base supports both Postgres DB and MS SQL DB.
* API authentication and authorization
* Common user profile
* Data footprint expands to include new entities such as asset, formation, well completion, well perforation and well zone.
* Meta data table enhancement
* Data footprint update existing entities include net work series tables, equipment master series tables. +
* Add common user profile to help user view account and permission information.
* API enhancement, supporting save parent with child and combined unique constraints recognition.
* Well detail page and homepage functionalities enhancement.
* Export enhancement.
* Filter add search for the reference columns.
* Grid view drop down of reference columns supports to search data in full of current table.
* Multiple column constraint values are relevant with each other when select in cell grid.

== What’s new in Joint MVP - June 2020

* Data footprint expands to include new entities such as well test, facilities, well activity, etc. +
* Admin panel to control user access and privileges.
* Home page which supports quickly search and navigate wells.
* Newly add and improve APIs.
