= Master, Operational, Reference

In the oil & gas industry, data is a big term. It encompasses many aspects of E&P activities, such as exploration, appraisal, drilling, development, and production. PDM 365 data model focuses on the data of production phase and aims to provide a unified data base source for production domain, and be easy to store in and retrieve from.

In PDM365, from data manager’s perspective, we can classify the data into master data, operational data three types.

== Master Data

Master data includes entities that are either static and/or rarely change over the life or the field. It includes:

* Organization Unit
* Field
* Pool/Reservoir
* Formation
* Zone
* Well
* Wellbore
* Well Completion and perforation
* Well Tubular
* Flow Model
* Facilities
* Equipment

== Operational Data

Operational data includes data that regularly and frequently change such as: production flow test data.

The production flow test is regularly run for wells to get the measured gas, water and oil when the well is working normally, which is helpful for tracking the well’s production over the long term. （https://greasebook.com/）

The operational data can be managed in PDM data model.

== Reference Data

Reference data are data that define the set of permissible values to be used by other data fields. Reference data gain in value when they are widely reused and widely referenced. Typically, they do not change overly much in terms of definition, apart from occasional. Such as reporting flow reference, which is used to store information for the types of volumes flow. For example, open inventory, closing inventory, production, injection, and disposition.

== Time Series Data

Time series data, also referred to as time-stamped data, is a sequence of data points indexed in time order. Time-stamped is data collected at different points in time.

These data points typically consist of successive measurements made from the same source over a time interval and are used to track change over time. (https://www.influxdata.com/what-is-time-series-data/[What is Time Series Data? | Definition, Examples, Types & Uses (influxdata.com)])

The time series data is not in the PDM main data base. PDM use MongoDB to manage the time series data.
