= Date Time and Coordinate

== Date Time and Time Zone

In oil and gas industry, there are historical data, and high frequency real time data. Presentation to users in different time-zones may need you adjust the time to adapt the different time zones. Sometimes you need to show the date and time in the user’s local time. Or you may need to display it in the original local time or as UTC time. You may also need to clearly state the actual time zone for that specific date. So depending on the requirement, you may need to know the proper time zone.

For this condition, when store the time in the database, you need to make additional data fields to save the time zone information to ensure that you can adapt the time zones.

*Date Time and Date*

For the date, which we will drop the time, the control type of it should be ``calenderWithDate''.

For the date, which we need record original local time, the control type of it should be ``calenderWithDateTime''. And there is a according time zone column for this date, and will add “_TZ” as postfix.

Example:

For the SPUD_DATE in well table, there is SPUD_DATE_TZ column, and whose foreign constraint is R_Timezone reference table.

*Time Zone Reference*

PDM uses ``R_TimeZone'' table to list the time zone items.

PDM uses Coordinated Universal Time(UTC). Such as UTC +1:00, UTC -1:00 as reference time zone.

An example of start time with specific time.

Start Time: 12/21/2021 8:00

Start Time Timezone: UTC +0:00

== Coordinates

In an oil filed, the wells, facilities has its own location. Take well as an example, the wellhead location and bottom hole location are commonly used to identify the well surface location and sub-surface production target location. User can project the well location information to GIS map or grid coordinates to do further analysis.

*Horizontal and Vertical Coordinates*

* Horizontal coordinates include northing, easting or x, y values (referred to as Grid coordinates) and latitude, longitude pairs (referred to as Geographic coordinates).
* Vertical coordinates usually refer to height, elevation or depth.

*X/Y Values*

* Horizontal coordinate values should be stored as Geographic values (latitude, longitude). Wherever possible, only the Geographic values should be kept; by keeping only one set of horizontal values, data integrity issues are minimized (you don’t have to keep two sets of coordinates in synch with each other).
* The X/Y attribute name is X_COORDINATE and Y_COORDINATE. The display name is X_LON and Y_LAT.

*X/Y Data type*

* The data type of the latitude/longitude is numeric.
* If the original data format is degree/minutes/seconds, need convert to decimal degrees and save into database.

*Coordinate Reference System*

* Latitude, Longitude values must be referenced to a coordinate reference system (CRS). The coordinate system references datum, spheroid and ellipsoid information, and transformations between CRS.

*Well Vertical Depth Reference*

* Maintain reference measurement point for depths. All depths are defined relative to some reference point. (i.e. measured depths in a wellbore are defined relative to a surface reference point such as the Kelly bushing) Keep depth reference point at the row level in the WELL table.
* The ``DEPTH_DATUM'' provide the depth reference, which is foreign constraint form table ``R_WELL_DATUM_TYPE'', which could be Kelly Bush Elevation, Ground Elevation, or other defined types.
