= Introduction

*Haul Event*

The oil and water hauls provide user and operators a form to record all tank events and activity for a given day, such as truck sales, water draw tickets, internal transfers, and hot injections. The haul event recorded the essential part of daily operations. It records the receipt of the quantity of fluid removed from a storage tank to a pipeline or a truck for sales and required for custody transfers.

The haul event form allows for several required data, such as Date, Cargo Control Number, Shipper, Carrier and measurement data, such as beginning and ending volumes, temperatures, free water, emulsion and BSW.

*Sale Statement*

Commonly the gas, such as net-gas, dry-gas is transported through pipeline. And if pipeline is not available, the gas needs to be liquified to LNG to be transported through truck tank. For the gas transported through pipeline, it is purchased by user directly, and the purchase volume is measured at a periodically interval, such as by month.

The sale statement provide user a form to record the gas measurement for a time period, such as start date, end date, gross volume, and wet basis. The seller, buyer, and price by unit is used to track the sale transaction information.
