= Data Model - Overview

== What this documentation is for

This documentation captures the data model that is implemented in the DecisionSpace 365 Production Data Management. This documentation is live - we are actively adding and extending the data model, and the additions will be documented here.

== How we design PDM365 data model

PDM365 data model is relational data model. PDM application supports Postgres and SQL Server 2 kinds of data base.

We prioritize *performance* and *extensibility* when designing the data model.

*Performance* means being fast. The data model should *NOT* be too excessive and complicated to the point that it slows down processes and queries, but still structured enough for fast indexing.

*Extensibility* means that the PDM365 data model provides a core definition that can be extended in a maintainable and sustainable way, over the life of the field. We are aware that trying to define _all_ possible entities and attributes throughout many kinds of assets and operations is a never-ending quest. With the PDM365 data model and application, new entities and attributes can be added and maintained out-of-the-box.

The standards that we consider and examine when defining the data model structure are:

* PPDM

* OSDU (Open Subsurface Data Universe)

* PRODML

* Project data management system - Openworks

* Landmark Common Model - LCM

* PE Data Model (from DS Production Engineer)

* PPDM-modified (from DS Production Allocation)

For entity definition, table names, and attribute definitions and constraints, we adhere to PPDM definition with minor modifications.

For example, we follow PPDM definition to use `Pool` and its definition _(POOL: Represents a reservoir or a group of small tracts of land brought together for the granting of a well permit under applicable spacing rules_)_._ However, we also modify it into ``Pool/Reservoir'' as display name in PDM application because the”Pool” terminology is not widely used outside North America.

== PPDM,OSDU and PRODML standards – how they relate to PDM365 data model

https://ppdm.org/ppdm/PPDM/IPDS/PPDM_Data_Model/PPDM/PPDM_3.9_Data_Model.aspx?hkey=c8aed1ca-aa85-409e-8d89-74b42a6d2a18[PPDM] has developed the industry standard and an extensive guideline on petroleum data model definition since 1988. https://www.opengroup.org/osdu/forum-homepage[OSDU] is the new industry initiative led by supermajors (BP, Chevron, Total, among others) to develop a standard data platform for the oil and gas industry, which will reduce silos and put data at the center of the subsurface community. https://www.energistics.org/portfolio/prodml-data-standards/[PRODML] is a set of standards for optimizing producing oil and gas wells, with a focus on data from the reservoir-wellbore boundary to the custody transfer point.

When developing PDM core data model, we examine PPDM 3.9 standard closely. We adhere to their entity definitions, table names, attribute definitions, and attribute constraints. However, we rethink the approach of the highly normalized table structure that comes with the standard, to ensure performance and extensibility taking priority over completeness/complexity. We seek to simplify the data structure and tables, reduce data redundancy and ensure consistency.

The https://ppdm.org/ppdm/PPDM/IPDS/PPDM_Data_Model/PPDM/PPDM_3.9_Data_Model.aspx?hkey=c8aed1ca-aa85-409e-8d89-74b42a6d2a18[PPDM3.9] is on PPDM website (membership required). The PDF version is available for v3.8.

On OSDU, we are closely monitoring the progress of the data modeling. It’s important to note that OSDU data definition is still under iteration. In the year 2021, OSDU defined the volume, well test and downtime event, and PDM refers to the standard and extend the data model.

On PRODML, we also examine the data transfer standard they defines. Especially in reporting volume and flow model module, PDM aligns the PRODML standards very closely.

== Features in PDM Data Model

PDM data model has covered the data definition of the use cases those the production optimization analysis features needed and as following:

* Entity definition

* Flexible hierarchy organization

* Reported volume

* Flow model

* Well test

* Production decline analysis

* Down time event

* Fluid analysis

Meanwhile, the data model provides the following advantages,

* Data consistency and integrity assurance

* Unique constraint

* Numerous data types

* Clear relationship and structure
