= PDA Phase

This content of major and dependent phase refers to Aries.

The major phase of a property is the main production stream for that property, for example, OIL or GAS.

A secondary phase is a producing stream other that the major producing stream. Secondary phases cannot last beyond the major phase life.

Typical secondary phases are:

* SGS - Default phase name used to define a secondary gas stream.
* CND - Default phase name used to define condensate

Normally user forecast major phase production directly, using a decline curve formula or a list of values. While user can also forecast other phases directly, these subordinate (sometimes called dependent or secondary) phases are usually physically dependent on the major phase production volumes.

For these dependent phased, user schedule the forecast indirectly based on forecasting their producing ratios.

For example, casing head gas from an oil well is forecast by scheduling the gas-oil ratio, usually referred to as the GOR. The GOR will be ``denominator'' of the major phase oil. And water can be included in forecast by scheduling WTR/OIL.

Similarly, condensate from a gas well is forecast by scheduling the condensate-gas ratio, called the yield. The keyword for this is OIL/GAS, or CND/GAS if you use a separate phase for condensate.

Other combinations of phases can be scheduled, such as NGL/GAS, as long as the ``denominator'' phase GAS has been scheduled. For example, you could schedule OIL as the major phase, use the ratio GAS/OIL for the second phase, and then use the ratio SUL/GAS for a third phase.
